Fixed Logging bug
When Log4r is included it can sometimes conflict with the base
Ruby Logger and cause problems like:

  undefined method `clear' for nil:NilClass (NoMethodError)

where clear is being called on an array @outputters that can never be nil
in the Log4r Logger class.